include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
